### ISSUE TITLE
Calling setFooter with newlines completely breaks output

### ISSUE THREAD

**Issue by Inrixia** [kamiyo/multi-progress-bars#20]
Calling setFooter with a string that contains newlines results in massive console spam and loading bars completely breaking. 
I presume this is due to the line counts being offset by the newlines.

Working:
```ts
this.mpb?.setFooter({
  message: `${processed} - ${downloaded} - ${speed}`,
  pattern: ' ',
});
```
Broken:
```ts
this.mpb?.setFooter({
  message: `${processed}\n${downloaded}\n${speed}`,
  pattern: ' ',
});
```

**Comment by Inrixia** [comment]
The same issue appears to occur if you use TABs

**Comment by kamiyo** [comment]
Should be fixed with version `v4.2.1`. Let me know.

**Comment by Inrixia** [comment]
Using newlines no longer cause glitching but anything not on the first line is just not displayed, I presume this is intentional?

**Comment by kamiyo** [comment]
Yes, I don't really know what would be the expected behavior in that case. I would prefer the library user do something like `stringWithNewlines.replace(/\n/g, ' - ')` or something depending on what the user wants, rather than me trying to decide. I could also just throw an Error, I guess, but that seems a bit hostile haha.

**Comment by Inrixia** [comment]
I reckon if it doesn't support newlines best to throw a error to inform the user its not supported, rather than quietly fail with unexpected behaviour. Using " - " works fine for me so I'm not majorly affected by it
