### ISSUE TITLE
CLI will start flickering when there are bars outside of the terminals view to draw.

### ISSUE THREAD

**Issue by Inrixia** [kamiyo/multi-progress-bars#5]
When there are enough bars that they go outside the terminals view a terminal update causes flickering.

Having the ability to remove bars or limit the amount would probably solve this issue. 
@Hezkezl

https://user-images.githubusercontent.com/6373693/111021034-9817f100-842e-11eb-8ab8-ef7c3306c7a0.mp4

**Comment by kamiyo** [comment]
I will take a look - I know this happens, even when it's not the bars overflowing, and will see if I can fix it. Are you doing it fixed to the top or bottom?

**Comment by Inrixia** [comment]
> Are you doing it fixed to the top or bottom?

Top at the moment, I get other issues unrelated to this if I use bottom.

**Comment by kamiyo** [comment]
@Inrixia I'm not able to quite repro the issue. I can manage to make it flicker sometimes in this case (with more Tasks than there are lines in the console), but not to the degree I see on the screen cap. Are all of the other tasks Finished besides the bottom one?

**Comment by kamiyo** [comment]
@Inrixia Another question, what are you using as the initMessage? It seems like there are two lines at the bottom instead of one, which is what I'd expect, but maybe my eyes deceive me.

Also, I _am_ going to change the logic so it only prints as many Tasks as there are lines (minus the empty line), so that'll probably solve the flickering, I'm just not able to get that drastic of a flickering.

**Comment by Hezkezl** [comment]
> @Inrixia I'm not able to quite repro the issue. I can manage to make it flicker sometimes in this case (with more Tasks than there are lines in the console), but not to the degree I see on the screen cap. Are all of the other tasks Finished besides the bottom one?

@kamiyo in my video (which Inrixia posted above), there's only one file downloading at a time. So yes, the other tasks have finished downloading besides the bottom one.

If I full screen it, then it gets truly nauseating to look at... I can sorta make it stop flickering by using my mouse to select a little bit of the window, but then it just stops moving entirely. I'm attaching a youtube video I just made as I was typing this up.

https://www.youtube.com/watch?v=IVN6sbZguBg

**Comment by Inrixia** [comment]
All the code for the bars is in this class: [VideoProcessor](https://github.com/Inrixia/Floatplane-Downloader/blob/d0ba3ca6a06e561cdf562622bf1425dbad8e5fd4/src/downloader.ts#L19)

Here is the [initMessage](https://github.com/Inrixia/Floatplane-Downloader/blob/d0ba3ca6a06e561cdf562622bf1425dbad8e5fd4/src/downloader.ts#L65) used.

**Comment by kamiyo** [comment]
Thanks, I think I got the repro now. As you suggested I will add a method
to remove tasks as well as clamp the number of currently rendered tasks to
window height (adjusted for some of the other things). I will also expose a
snapshot method to get the progress buffer as a string in case you want to
print out all of the tasks without truncating at the very end after all
tasks are done.

**Comment by kamiyo** [comment]
Standby for a new alpha version with this stuff fixed, hopefully.

**Comment by kamiyo** [comment]
Published an alpha - multi-progress-bars@4.0.0-alpha.0

See if this solves the problem. Let me know if there are any bugs or strange behavior that you notice.

**Comment by Inrixia** [comment]
Re the issue above it looks like this is still occurring in 4.0.0. Is there anything I need to be doing side from having updated?

**Comment by kamiyo** [comment]
Hi, I will take a look at the code in your library and see what's going on. Could be some edge case, or my logic is incomplete.

**Comment by Inrixia** [comment]
Thanks. Let me know if you need anything explained

**Comment by kamiyo** [comment]
Hey, I have a couple of questions, because I'm at the surface unable to repro the issue referenced in your library issues. I will open an issue on your library, and link this one there.

**Comment by kamiyo** [comment]
Okay, so you mentioned in https://github.com/Inrixia/Floatplane-Downloader/issues/102 two possibilities:

Removing completed tasks: v4+ of mpb actually has `removeTask(taskName)`, if you wish to remove completed bars (rather than have the library truncate to window size automatically).

Status bar: If you want to print pinned information, as I mentioned, mpb has borders, or more precisely, a header and footer. You can use something like ``setFooter({ pattern: '-', message: `Total downloaded: ${numDone} / ${totalDownloads}`, right: 4 })`` to set some information in the footer that is right-align anchored to 4 from the right of the screen. Obviously if you have a lot of info to display, it could get crowded.

Finally, you can always use `console.log` (which mpb overrides to make it print above the progress bars) so that it won't interfere with the progress bar display.

p.s. I realized just now I didn't add the header and footer API to the docs (only a mention in the Usage), so I will do that shortly.

**Comment by Inrixia** [comment]
Will def take advantage of removeTask and try out setFooter. Currently the console.log is being utilized for the display its just set to go below the bars instead of above as I found that to have better support.

**Comment by kamiyo** [comment]
I see. If you're using `process.stdout.write` whatever you print is going to be overwritten by the next mpb render update, since mpb resets the terminal cursor to upper left and clears the screen to draw the next render. If you print stuff under the bars, it will push the bars up past the break (as is normal terminal behavior), and then the next mpb will erase the screen and redraw, hence the jumping around. And, if you scroll up, I'm thinking you'll some bars, and none of your stdout writes... I think. Part of the point of mpb is that it will keep track of the console logs and, if the bars start taking up too much real estate, push the logs above the break first before rendering the progress bars. On the other hand, I'm not sure even if you use console.log, it won't jump, especially with a multi-line log.

In any case, try those two options and see how it goes.

**Comment by Inrixia** [comment]
Thanks for the great advice of using `setFooter` have got it working and looks like its fixed the flickering. Though did run into two bugs that I've opened issues for https://github.com/kamiyo/multi-progress-bars/issues/20, https://github.com/kamiyo/multi-progress-bars/issues/19

I also tried using `removeTask` but it does not appear to do anything, nor is it present in the wiki so maybe it's not been implemented yet? Regardless being able to remove tasks is minor and the main issue has been resolved so thanks again
